export const Armors = [
    {
        "type":"armor",
        "defence":3,
        "price":50,
        "sellPrice":10,
    },
    {
        "type":"armor",
        "defence":7,
        "price":250,
        "sellPrice":100,
    },
    {
        "type":"armor",
        "defence":8,
        "price":800,
        "sellPrice":300,
    }
]